/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': '#0A0A0A',
        'bg-secondary': '#111111',
        'bg-tertiary': '#1A1A1A',
        'bg-frost': 'rgba(255, 255, 255, 0.05)',
        'accent-gold': '#D4AF37',
        'accent-gold-light': '#E8D44D',
        'accent-gold-dark': '#AA8C2C',
        'text-primary': '#FFFFFF',
        'text-secondary': '#A0A0A0',
        'text-tertiary': '#666666',
        'text-gold': '#D4AF37',
        'success': '#2EC4B6',
        'warning': '#E8A838',
        'danger': '#E63946',
        'info': '#00B4D8',
        'stage-influent': '#0066CC',
        'stage-sediment': '#4A90D9',
        'stage-carbon': '#5C6B73',
        'stage-pressure': '#E63946',
        'stage-booster': '#00B4D8',
        'stage-ydivider': '#7B61FF',
        'stage-ro': '#00E5FF',
        'stage-nf': '#2EC4B6',
        'stage-mixer': '#9B5DE5',
        'stage-minerals': '#FFD700',
        'stage-uvuf': '#F8F9FA',
        'stage-output': '#90E0EF',
        'stage-waste': '#FF6B6B',
        'stage-hud': '#00F5FF',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        'display': ['Playfair Display', 'Georgia', 'serif'],
        'body': ['Inter', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-gold": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "scroll-line": {
          "0%, 100%": { transform: "scaleY(0.5)", opacity: "0.5" },
          "50%": { transform: "scaleY(1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "shimmer": "shimmer 1.5s infinite",
        "pulse-gold": "pulse-gold 2s ease-in-out infinite",
        "float": "float 4s ease-in-out infinite",
        "scroll-line": "scroll-line 2s ease-in-out infinite",
      },
      backgroundImage: {
        'gradient-gold': 'linear-gradient(135deg, #D4AF37 0%, #E8D44D 50%, #AA8C2C 100%)',
        'gradient-hero': 'linear-gradient(180deg, #0A0A0A 0%, #111111 50%, #0A0A0A 100%)',
        'gradient-water': 'linear-gradient(180deg, #00B4D8 0%, #2EC4B6 50%, #0066CC 100%)',
        'gradient-card': 'linear-gradient(180deg, rgba(255,255,255,0.08) 0%, rgba(255,255,255,0.02) 100%)',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
